name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3   
    - name: XCode Build Archive
      uses: yukiarrr/ios-build-action@v1.5.0
      with:
          project-path: Resnet50Demo.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.PROVISIONING_PROFILE }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          configuration: Debug
          output-path: app-debug.ipa
          export-method: ad-hoc
    - name: Distribute iOS app
      run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "file=@/Users/runner/work/Build/Products/app-debug.ipa" \
            -F "message=　・ test upload" \ 
            "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
