name: iOS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version 13.2.1
      run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
   
    - name: XCode Build Archive
      uses: yukiarrr/ios-build-action@v1.3.0
      with:
          project-path: Resnet50Demo.xcodeproj
          p12-key-base64: ${{ secrets.P12_BASE64 }}
          p12-key-password: ${{ secrets.P12_PASSWORD }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.PROVISIONING_PROFILE }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          configuration: Debug
          output-path: app-debug.ipa
          export-method: ad-hoc
    - name: Distribute iOS app
      run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "file=@/Users/runner/work/Build/Products/app-debug.ipa" \
            -F "message=　・ test upload" \ 
            "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
